name = "agstrand-com-cf-worker"
account_id = "6c70984c450202a9506a437c273e742d"
workers_dev = true
main = "worker.js"
compatibility_date = "2023-11-06"
node_compat = true

route = { pattern = "agstrand.com", custom_domain = true }

[build]
command = "if ! [ -d ./assets ] ; then mkdir ./assets ; fi && if ! [ -d ./.cwd ] ; then mkdir ./.cwd ; fi"
cwd = ".cwd"

[site]
bucket = "./assets"
include = ["./assets"]

[placement]
mode = "smart"
